name: Sync to test2

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: Giftgrass/test # Source repository
          token: ${{ secrets.PAT_TOKEN }} # Use your Personal Access Token (PAT)

      - name: Add target repository as remote
        run: |
          git remote add target https://github.com/Giftgrass/test2.git
          git fetch target

      - name: Reset target repository to match source repository
        run: |
          git push --force target main:main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use your Personal Access Token