name: Sync to test2

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} # Use your Personal Access Token (PAT)

      - name: Sync with target repository
        uses: repo-sync/github-sync@v2
        with:
          source_repo: Giftgrass/test.git # Source repository
          source_branch: main # Sync from the main branch
          destination_branch: main # Sync to the main branch of the target repo
          github_token: ${{ secrets.PAT_TOKEN }} # Use your Personal Access Token