name: Laravel Setup, Test, Update, and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

  update-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        client: [
          { name: 'test1', url: 'Giftgrass/test1' },
          { name: 'test2', url: 'Giftgrass/test2' }
        ]

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Debug current directory
        run: pwd

      - name: Clone client repository
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh repo clone ${{ matrix.client.url }} client-repo

      - name: Navigate to client repository
        run: |
          cd client-repo
          echo "Current directory: $(pwd)"
          git remote -v

      - name: Pull changes from source repository
        run: |
          cd client-repo
          git remote add source "https://github.com/${{ github.repository }}.git"
          git fetch source
          git reset --hard source/main

      - name: Push changes to client repository
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd client-repo
          git remote set-url origin "https://$GH_TOKEN@${{ matrix.client.url }}"
          git push origin main --force