name: Sync to test1

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} # Use your Personal Access Token (PAT)

      - name: Sync with target repository
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }} # This is the 'test' repo (source)
          source_branch: main # Sync from the main branch
          target_repo: Giftgrass/test1 # Replace with the full name of the target repo
          target_branch: main # Sync to the main branch of test1
          github_token: ${{ secrets.PAT_TOKEN}} # Use your Personal Access Token