
name: Laravel Setup, Test, Update, and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

#      - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.2'

#     - name: Install dependencies
#       run: composer install

#     - name: Set up Laravel environment
#       run: |
#         cp .env.example .env
#         php artisan key:generate

  test:
    runs-on: ubuntu-latest
    needs: setup

#  services:
#     mysql:
#       image: mysql:5.7
#       env:
#         MYSQL_ROOT_PASSWORD: root
#         MYSQL_DATABASE: homestead
#         MYSQL_USER: homestead
#         MYSQL_PASSWORD: secret
#       ports:
#         - 3306:3306
#       options: >-
#         --health-cmd="mysqladmin ping --silent"
#         --health-interval=10s
#         --health-timeout=5s
#         --health-retries=3

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

#    - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '7.4'

#     - name: Install dependencies
#       run: composer install

#     - name: Set up Laravel environment
#       run: |
#         cp .env.example .env
#         php artisan key:generate

#     - name: Set environment variables and Database
#       run: |
#         echo "DB_CONNECTION=mysql" >> .env
#         echo "DB_HOST=127.0.0.1" >> .env
#         echo "DB_PORT=3306" >> .env
#         echo "DB_DATABASE=homestead" >> .env
#         echo "DB_USERNAME=homestead" >> .env
#         echo "DB_PASSWORD=secret" >> .env

  update-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        client: [
          { name: 'test2', url: 'github.com/Giftgrass/test2.git' }
#          { name: 'ENKOSIBAWO', url: 'github.com/Grasshopper-Green-Technologies/enkosibawo-portal.git' },
#          { name: 'ISIDINGO PROJECTS', url: 'github.com/Grasshopper-Green-Technologies/isidingo-portal.git' },
#          { name: 'Likhonalethu', url: 'github.com/Grasshopper-Green-Technologies/likhonalethu-portal.git' },
#          { name: 'RCWBA TRADING', url: 'github.com/Grasshopper-Green-Technologies/rcwba-portal.git' },
#          { name: 'SAKHULU PROJECTS', url: 'github.com/Grasshopper-Green-Technologies/sakhulu-portal.git' },
#          { name: 'MILANOSI', url: 'github.com/Grasshopper-Green-Technologies/milanosi-portal.git' },
#          { name: 'PHOLA AND LUGIE', url: 'github.com/Grasshopper-Green-Technologies/phola-lugie-portal.git' },
#          { name: 'FATYELA', url: 'github.com/Grasshopper-Green-Technologies/fatyela-portal.git' },
#          { name: 'ISIZWE SETHU AND SONS GENERAL', url: 'github.com/Grasshopper-Green-Technologies/isizwe-portal.git' },

        ]

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Update and Deploy
        env:
            GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
              gh repo clone Giftgrass/test2 client-repo
              git remote add source "https://github.com/${{ github.repository }}.git"
              git pull source main
              git push origin main
