name: multipleRepoUpdate

on:
  workflow_run:
    workflows: ["laravel"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Git Status
        run: |
          git status
          git branch
          git remote -v
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to multiple repos
        run: |
          echo "Adding test1 remote..."
          git remote add test1 https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Giftgrass/test1.git
          echo "Pushing to test1..."
          git push test1 main --force
          
          echo "Adding test2 remote..."
          git remote add test2 https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Giftgrass/test2.git
          echo "Pushing to test2..."
          git push test2 main --force
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}