name: multipleRepoUpdate

on:
  workflow_run:
    workflows: ["laravel"] 
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Git status:"
          git status
          echo "Git remote:"
          git remote -v

      - name: Push to test2
        run: |
          echo "Adding remote..."
          git remote add test2 git@github.com:Giftgrass/test2.git
          echo "Remote added, checking remotes..."
          git remote -v
          echo "Attempting push..."
          git push test2 main --force
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}