name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync Repositories
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PAT_TOKEN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Debug SSH
      run: ssh -vT git@github.com

    - name: Sync with Repo2
      run: |
        git remote add test2 git@github.com:Giftgrass/test2.git
        git push -f test2 main

    - name: Sync with Repo3
      run: |
        git remote add test1 git@github.com:Giftgrass/test1.git
        git push -f test1 main