name: multipleRepoUpdate

on:
  workflow_run:
    workflows: ["laravel"] 
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Debug Info
        run: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Git status:"
          git status
          echo "Git remote:"
          git remote -v

      - name: Push to test1 and test2
        run: |
          echo "Adding remote..."
          git remote add test1 git@github.com:Giftgrass/test1.git
          echo "Remote added, checking remotes..."
          git remote -v
          echo "Attempting push..."
          git push test1 main --force
          echo "Adding remote..."
          git remote add test2 git@github.com:Giftgrass/test2.git
          echo "Remote added, checking remotes..."
          git remote -v
          echo "Attempting push..."
          git push test2 main --force
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}