name: multipleRepoUpdate

on:
  workflow_run:
    workflows: ["laravel"] 
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to multiple repos (as in your original workflow)
        run: |
          git remote add test1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Giftgrass/test1.git
          git push test1 main --force

          git remote add test2 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Giftgrass/test2.git
          git push test2 main --force

          
