name: Mirror Changes to Test1 and Test2

on:
  push: # Trigger the workflow on push to the main branch
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository (test)
      - name: Checkout source repo
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Mirror to Test1
      - name: Push changes to Test1
        run: |
          git remote add test1 https://x-access-token:${{ secrets.MIRROR_REPO_PAT }}@github.com/Giftgrass/test1.git
          git push --mirror test1

      # Step 4: Mirror to Test2
      - name: Push changes to Test2
        run: |
          git remote add test2 https://x-access-token:${{ secrets.MIRROR_REPO_PAT }}@github.com/Giftgrass/test2.git
          git push --mirror test2